# Array

In [7]:
import numpy as np
y=np.array([1,2,3,4])
print(y)
# array type
print (type(y))
# to check the dimension of Array
print(y.ndim)



[1 2 3 4]
<class 'numpy.ndarray'>
1


In [6]:
# to store value in array
l=[]
for i in range(1,5):
    int_1=int(input("Enter:"))
    l.append(int_1)
print(np.array(l))


Enter:7
Enter:9
Enter:9
Enter:09
[7 9 9 9]


In [10]:
# two dimension array
arr2=np.array([[1,2,4,5],[5,9,4,7]])
print(arr2)
print(arr2.ndim)

[[1 2 4 5]
 [5 9 4 7]]
2


In [11]:
# three dimension array
arr3=np.array([[[1,3,6,7],[5,99,89,9]]])
print(arr3)
print(arr3.ndim)

[[[ 1  3  6  7]
  [ 5 99 89  9]]]
3


In [15]:
# multiple dimension array
#arrn=np.array([1,8,9,9], ndimn= 10)
#print(arrn)
#print(arrn.ndim)

TypeError: array() got an unexpected keyword argument 'ndimn'